version: "3"

services:
  db:
    image: mysql:8.0
    ports:
      - 8080:3306
    networks:
      - celsia-prueba-net
    environment:
      - MYSQL_DATABASE=celsia-prueba-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=user

  api:
    build: .
    ports:
      - 8081:8080
    networks:
      - celsia-prueba-net
    environment:
      - DB_HOST=db
      - DB_PORT=8080
      - DB_USER=user
      - DB_PASSWORD=user
    depends_on:
      - db

networks:
  celsia-prueba-net: